[google]
client_id = "1029577774779-bo3c1l6ifbd1bpnj1rlsdp7qnmhdoebh.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://form-creator.streamlit.app"
